#!/usr/bin/env python3
"""
ACR-QA Feature 4 — Autofix PR Bot
Opens a GitHub PR containing only AI-generated fixes that passed linter validation.
Fix code is read from the database (fix_validated=True, fix_code not null).
Uses GitHub API blobs — no local file manipulation required.
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from github import Github, GithubException

from DATABASE.database import Database

logger = logging.getLogger(__name__)


def build_pr_body(fixes: list[dict], run_id: int) -> str:
    high = [f for f in fixes if f.get("canonical_severity") == "high"]
    medium = [f for f in fixes if f.get("canonical_severity") == "medium"]
    low = [f for f in fixes if f.get("canonical_severity") == "low"]

    lines = [
        "## ACR-QA Autofix PR",
        "",
        f"This PR contains **{len(fixes)} validated AI-generated fix(es)** for run `#{run_id}`.",
        "Every fix passed linter validation before being included.",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| High | {len(high)} |",
        f"| Medium | {len(medium)} |",
        f"| Low | {len(low)} |",
        "",
        "---",
        "",
        "### Fixes Applied",
        "",
    ]

    for fix in fixes:
        sev = fix.get("canonical_severity", "low").upper()
        rule = fix.get("canonical_rule_id", "UNKNOWN")
        fpath = fix.get("file_path", "unknown")
        line = fix.get("line_number", 0)
        msg = fix.get("message", "")
        conf = fix.get("fix_confidence", "unknown")
        lines += [
            f"#### {sev} — {rule}",
            f"- **File:** `{fpath}:{line}`",
            f"- **Issue:** {msg}",
            f"- **Fix confidence:** {conf}",
            "",
        ]

    lines += [
        "---",
        "",
        "### Review Checklist",
        "- [ ] All fixes are correct and do not change behaviour",
        "- [ ] Tests pass after applying these fixes",
        "- [ ] No unintended side effects",
        "",
        "---",
        "*Generated by ACR-QA v3.0.6 — Automated Code Review and Quality Assurance*",
    ]
    return "\n".join(lines)


def create_fix_pr(run_id: int, github_token: str, repo_name: str, base_branch: str = "main") -> None:
    logger.info(f"ACR-QA Autofix PR — run #{run_id}")

    db = Database()
    fixes = db.get_validated_fixes(run_id)

    if not fixes:
        logger.info("No validated fixes found for this run — nothing to PR.")
        logger.info("Fixes are only available for findings where the AI suggested a fix")
        logger.info("and it passed linter validation (fix_validated=True).")
        sys.exit(0)

    logger.info(f"Found {len(fixes)} validated fix(es)")
    for f in fixes:
        logger.info(
            f"  {f['canonical_severity'].upper()} {f['canonical_rule_id']} "
            f"@ {f['file_path']}:{f['line_number']} "
            f"(confidence: {f['fix_confidence']})"
        )

    gh = Github(github_token)
    try:
        repo = gh.get_repo(repo_name)
    except GithubException as e:
        logger.info(f"Cannot access repo {repo_name}: {e}")
        sys.exit(1)

    branch_name = f"acrqa-autofix-run-{run_id}"

    # Get base branch SHA
    try:
        base_ref = repo.get_git_ref(f"heads/{base_branch}")
        base_sha = base_ref.object.sha
    except GithubException as e:
        logger.info(f"Cannot get base branch {base_branch!r}: {e}")
        sys.exit(1)

    # Create or reset the fix branch
    try:
        existing = repo.get_git_ref(f"heads/{branch_name}")
        existing.edit(sha=base_sha, force=True)
        logger.info(f"Reset existing branch: {branch_name}")
    except GithubException:
        repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)
        logger.info(f"Created branch: {branch_name}")

    # Group fixes by file
    fixes_by_file: dict[str, list[dict]] = {}
    for fix in fixes:
        fp = fix["file_path"]
        fixes_by_file.setdefault(fp, []).append(fix)

    committed_files = []

    for file_path, file_fixes in fixes_by_file.items():
        try:
            file_obj = repo.get_contents(file_path, ref=base_branch)
            original_lines = file_obj.decoded_content.decode("utf-8").splitlines(keepends=True)
        except GithubException as e:
            logger.info(f"Cannot read {file_path} from repo: {e} — skipping")
            continue

        # Apply fixes: replace the flagged line with the validated fix code
        # Sort fixes by line descending so line numbers stay valid after edits
        file_fixes_sorted = sorted(file_fixes, key=lambda x: x["line_number"], reverse=True)
        patched_lines = original_lines.copy()

        for fix in file_fixes_sorted:
            line_idx = fix["line_number"] - 1
            if 0 <= line_idx < len(patched_lines):
                fix_code = fix["fix_code"].rstrip("\n") + "\n"
                patched_lines[line_idx] = fix_code

        patched_content = "".join(patched_lines)

        rules_applied = ", ".join(f["canonical_rule_id"] for f in file_fixes)
        commit_msg = f"fix({Path(file_path).name}): ACR-QA autofix — {rules_applied}"

        try:
            file_obj_branch = repo.get_contents(file_path, ref=branch_name)
            repo.update_file(
                file_path,
                commit_msg,
                patched_content,
                file_obj_branch.sha,
                branch=branch_name,
            )
            committed_files.append(file_path)
            logger.info(f"Committed fix for {file_path}")
        except GithubException as e:
            logger.info(f"Failed to commit {file_path}: {e}")

    if not committed_files:
        logger.info("No files could be committed — aborting PR creation")
        sys.exit(1)

    # Create PR
    pr_title = f"ACR-QA Autofix — {len(fixes)} validated fix(es) (Run #{run_id})"
    pr_body = build_pr_body(fixes, run_id)

    # Delete existing open autofix PR for this run if any
    for pr in repo.get_pulls(state="open", head=f"{repo.owner.login}:{branch_name}"):
        pr.edit(state="closed")
        logger.info(f"Closed existing PR #{pr.number}")

    try:
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=base_branch,
        )
        logger.info(f"PR created: {pr.html_url}")
        logger.info(f"PR number: #{pr.number}")

        # Write PR URL to file for workflow summary
        try:
            with open("/tmp/acr_fix_pr_url.txt", "w") as fh:
                fh.write(pr.html_url)
        except OSError:
            pass

    except GithubException as e:
        logger.info(f"Failed to create PR: {e}")
        sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser(description="ACR-QA Feature 4 — Autofix PR Bot")
    parser.add_argument("--run-id", type=int, required=True, help="Analysis run ID from ACR-QA")
    parser.add_argument("--repo", required=True, help="GitHub repository (owner/repo)")
    parser.add_argument("--base-branch", default="main", help="Base branch for the PR (default: main)")
    parser.add_argument("--token", help="GitHub token (or set GITHUB_TOKEN env var)")
    args = parser.parse_args()

    token = args.token or os.getenv("GITHUB_TOKEN")
    if not token:
        logger.info("GitHub token required — pass --token or set GITHUB_TOKEN")
        sys.exit(1)

    create_fix_pr(args.run_id, token, args.repo, args.base_branch)


if __name__ == "__main__":
    main()
