#!/usr/bin/env python3
"""
Create GitHub PR with auto-fixes
"""

import argparse
import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from github import Github

from CORE.engines.autofix import AutoFixEngine, apply_fixes
from DATABASE.database import Database


def create_fix_pr(run_id: int, github_token: str, repo_name: str):
    """
    Create a GitHub PR with auto-fixes for a run

    Args:
        run_id: Analysis run ID
        github_token: GitHub personal access token
        repo_name: Repository name (owner/repo)
    """
    print(f"🔧 Creating auto-fix PR for run #{run_id}")

    # Initialize
    db = Database()
    engine = AutoFixEngine()
    gh = Github(github_token)
    repo = gh.get_repo(repo_name)

    # Get findings
    findings = db.get_findings_with_explanations(run_id)
    print(f"   Found {len(findings)} findings")

    # Generate fixes
    fixes = []
    for finding in findings:
        fix = engine.generate_fix(finding)
        if fix:
            fixes.append(fix)

    if not fixes:
        print("   ❌ No auto-fixable issues found")
        return

    print(f"   ✓ Generated {len(fixes)} fixes")

    # Create branch
    branch_name = f"acrqa-autofix-run-{run_id}"
    base_branch = repo.default_branch

    print(f"   Creating branch: {branch_name}")

    try:
        # Get base commit
        base_ref = repo.get_git_ref(f"heads/{base_branch}")
        base_sha = base_ref.object.sha

        # Create new branch
        repo.create_git_ref(f"refs/heads/{branch_name}", base_sha)
        print("   ✓ Branch created")
    except Exception as e:
        print(f"   ⚠️  Branch might already exist: {e}")

    # Apply fixes locally
    print("   Applying fixes...")
    changes_by_file = apply_fixes(fixes)

    # Commit changes
    for file_path, changes in changes_by_file.items():
        print(f"   📝 {file_path}: {len(changes)} changes")

        # Read file content
        with open(file_path) as f:
            content = f.read()

        try:
            # Get file from repo
            file_obj = repo.get_contents(file_path, ref=branch_name)

            # Update file
            commit_message = f"Fix: {', '.join(changes[:3])}"
            if len(changes) > 3:
                commit_message += f" (+{len(changes) - 3} more)"

            repo.update_file(file_path, commit_message, content, file_obj.sha, branch=branch_name)
            print(f"   ✓ Committed {file_path}")
        except Exception as e:
            print(f"   ✗ Error committing {file_path}: {e}")

    # Create PR
    pr_title = f"🤖 ACR-QA Auto-fixes (Run #{run_id})"
    pr_body = f"""## Auto-generated Fixes

This PR contains automatic fixes for issues detected by ACR-QA.

### Summary
- **Run ID:** {run_id}
- **Fixes Applied:** {len(fixes)}
- **Files Changed:** {len(changes_by_file)}

### Changes by File
"""

    for file_path, changes in changes_by_file.items():
        pr_body += f"\n**{file_path}**\n"
        for change in changes:
            pr_body += f"- {change}\n"

    pr_body += """
### Review Checklist
- [ ] All fixes are correct
- [ ] Tests pass
- [ ] No unintended changes

---
*Generated by [ACR-QA](https://github.com/ahmed-145/ACR-QA) v2.0*
"""

    try:
        pr = repo.create_pull(title=pr_title, body=pr_body, head=branch_name, base=base_branch)

        print("\n✅ PR Created!")
        print(f"   URL: {pr.html_url}")
        print(f"   Number: #{pr.number}")

        return pr
    except Exception as e:
        print(f"\n❌ Error creating PR: {e}")
        return None


def main():
    parser = argparse.ArgumentParser(description="Create auto-fix PR")
    parser.add_argument("--run-id", type=int, required=True, help="Analysis run ID")
    parser.add_argument("--repo", required=True, help="Repository (owner/repo)")
    parser.add_argument("--token", help="GitHub token (or use GITHUB_TOKEN env)")

    args = parser.parse_args()

    token = args.token or os.getenv("GITHUB_TOKEN")
    if not token:
        print("❌ GitHub token required (--token or GITHUB_TOKEN env)")
        sys.exit(1)

    create_fix_pr(args.run_id, token, args.repo)


if __name__ == "__main__":
    main()
