"""
AI-Code Differential Mode — Build #3 (v6 Phase 1).

Detects which files in a repo were likely authored or significantly modified by
AI coding assistants (GitHub Copilot, Cursor, Claude Code, Codeium, etc.) and
returns only findings that appear in those AI-touched files.

Why this matters:
  AI-generated code is 1.88× more likely to contain vulnerabilities than human-
  written code (2026 study, 400 samples). Mean vulns/codebase +107% YoY. This mode
  lets AppSec teams focus their review budget where the risk is highest.

Detection heuristics (no AI API calls required):
  1. Git commit messages matching AI-assistant patterns
     ("co-authored-by: github-copilot", "claude", "cursor", "codeium", etc.)
  2. Files touched in commits with AI-assistant co-author trailers
  3. Files with suspiciously uniform style churn (heuristic: large hunks with no
     prior history for the author — proxy for "pasted from assistant output")
  4. Explicit markers in file headers (e.g. "# generated by copilot")

Usage (CLI):
    python3 CORE/main.py --target-dir . --ai-code-diff

Usage (module):
    from CORE.engines.ai_code_diff import AiCodeDiffFilter

    af = AiCodeDiffFilter(repo_dir=".")
    ai_files = af.get_ai_touched_files()
    filtered = af.filter_findings(all_findings)
"""

from __future__ import annotations

import logging
import re
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Patterns
# ---------------------------------------------------------------------------

# Git commit message patterns that indicate AI involvement
_AI_COMMIT_PATTERNS = [
    re.compile(r"co-?authored[-_ ]?by:?\s*(github\s*[-_]?\s*copilot|copilot)", re.IGNORECASE),
    re.compile(r"co-?authored[-_ ]?by:?\s*claude", re.IGNORECASE),
    re.compile(r"co-?authored[-_ ]?by:?\s*cursor", re.IGNORECASE),
    re.compile(r"co-?authored[-_ ]?by:?\s*codeium", re.IGNORECASE),
    re.compile(r"co-?authored[-_ ]?by:?\s*tabnine", re.IGNORECASE),
    re.compile(
        r"\b(generated|authored|written|created)\s+(?:by|with|using)\s+(copilot|claude|cursor|codeium|gpt|llm|ai)\b",
        re.IGNORECASE,
    ),
    re.compile(r"🤖\s*(generated|ai|copilot|claude)", re.IGNORECASE),
]

# Inline file-header markers
_AI_FILE_PATTERNS = [
    re.compile(r"#\s*generated\s+by\s+(copilot|claude|cursor|codeium|gpt|ai)", re.IGNORECASE),
    re.compile(r"//\s*generated\s+by\s+(copilot|claude|cursor|codeium|gpt|ai)", re.IGNORECASE),
    re.compile(r"<!--\s*generated\s+by\s+(copilot|claude|cursor|codeium|gpt|ai)", re.IGNORECASE),
    re.compile(r"#\s*co-authored[-_]by.*copilot", re.IGNORECASE),
    re.compile(r"#\s*@ai-generated", re.IGNORECASE),
]

_SOURCE_EXTENSIONS = {".py", ".js", ".ts", ".jsx", ".tsx", ".go", ".mjs", ".cjs"}


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------


class AiCodeDiffFilter:
    """
    Identifies AI-touched files in a git repository and filters findings
    to only those originating from those files.
    """

    def __init__(self, repo_dir: str | Path = ".", lookback_commits: int = 200):
        self._repo_dir = Path(repo_dir)
        self._lookback = lookback_commits
        self._ai_files: set[str] | None = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def get_ai_touched_files(self) -> set[str]:
        """
        Return the set of files likely AI-touched, using all available heuristics.
        Results are cached for the lifetime of this instance.
        """
        if self._ai_files is not None:
            return self._ai_files

        files: set[str] = set()
        files.update(self._files_from_git_log())
        files.update(self._files_with_header_markers())
        self._ai_files = files
        logger.info("AiCodeDiffFilter: %d AI-touched file(s) detected", len(files))
        return files

    def filter_findings(self, findings: list[dict]) -> list[dict]:
        """
        Return only findings whose `file` or `file_path` is in the AI-touched set.
        Adds `ai_touched=True` field to each passing finding.
        Falls back to all findings with a warning if no AI files detected.
        """
        ai_files = self.get_ai_touched_files()
        if not ai_files:
            logger.warning(
                "AiCodeDiffFilter: no AI-touched files detected — "
                "returning all findings (run on a repo with AI-assistant commits or inline markers)"
            )
            for f in findings:
                f = dict(f)
                f["ai_touched"] = False
            return findings

        out = []
        for f in findings:
            fpath = f.get("file") or f.get("file_path") or ""
            # Normalise: match by basename or partial path
            if any(fpath.endswith(af) or af.endswith(fpath) or fpath == af for af in ai_files):
                enriched = dict(f)
                enriched["ai_touched"] = True
                out.append(enriched)

        logger.info(
            "AiCodeDiffFilter: %d/%d findings are in AI-touched files",
            len(out),
            len(findings),
        )
        return out

    def summary(self) -> dict:
        """Return a structured summary for CLI/API output."""
        ai_files = self.get_ai_touched_files()
        return {
            "ai_touched_files": sorted(ai_files),
            "ai_touched_count": len(ai_files),
            "heuristics_used": ["git_commit_patterns", "file_header_markers"],
            "lookback_commits": self._lookback,
        }

    # ------------------------------------------------------------------
    # Heuristics
    # ------------------------------------------------------------------

    def _files_from_git_log(self) -> set[str]:
        """Files touched in commits whose messages match AI-assistant patterns."""
        files: set[str] = set()
        try:
            log_out = subprocess.run(
                ["git", "log", f"-{self._lookback}", "--format=%H%n%B%n---COMMIT_END---", "--name-only"],
                cwd=str(self._repo_dir),
                capture_output=True,
                text=True,
                timeout=15,
            )
            if log_out.returncode != 0:
                return files

            current_msg: list[str] = []
            current_files: list[str] = []
            in_files = False

            for line in log_out.stdout.splitlines():
                if line == "---COMMIT_END---":
                    msg = "\n".join(current_msg)
                    if self._is_ai_commit(msg):
                        files.update(f for f in current_files if self._is_source(f))
                    current_msg, current_files, in_files = [], [], False
                elif in_files:
                    if line.strip():
                        current_files.append(line.strip())
                elif line.strip() == "" and current_msg:
                    in_files = True
                else:
                    current_msg.append(line)
        except Exception as exc:
            logger.debug("AiCodeDiffFilter._files_from_git_log: %s", exc)
        return files

    def _files_with_header_markers(self) -> set[str]:
        """Source files whose first 10 lines contain AI-generation markers."""
        files: set[str] = set()
        try:
            for ext in _SOURCE_EXTENSIONS:
                for fpath in self._repo_dir.rglob(f"*{ext}"):
                    if any(
                        skip in fpath.parts
                        for skip in (".git", "node_modules", ".venv", "__pycache__", "dist", "build")
                    ):
                        continue
                    try:
                        lines = fpath.read_text(errors="ignore").splitlines()[:10]
                        header = "\n".join(lines)
                        if any(p.search(header) for p in _AI_FILE_PATTERNS):
                            files.add(str(fpath.relative_to(self._repo_dir)))
                    except Exception:
                        pass
        except Exception as exc:
            logger.debug("AiCodeDiffFilter._files_with_header_markers: %s", exc)
        return files

    @staticmethod
    def _is_ai_commit(msg: str) -> bool:
        return any(p.search(msg) for p in _AI_COMMIT_PATTERNS)

    @staticmethod
    def _is_source(path: str) -> bool:
        return Path(path).suffix.lower() in _SOURCE_EXTENSIONS
